version: '3.1'

services:
  task-tracker-api:
    build: './task-tracker-api'
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_NAME: 'db'
      DB_USER: 'admin'
      DB_PASSWORD: 'admin'
      JWT_SECRET: 'YmZkamxuZHZkZnZmZXdrcndsa3J3bmtsd3hjMTI4MW5zZGZzZGY'
      CORS_ALLOWED_ORIGINS: 'http://localhost:80'
    depends_on:
      - mysql
      - kafka
      - zookeeper

  task-tracker-frontend:
    build: './task-tracker-frontend'
    restart: always
    environment:
      API_URL: 'http://localhost:8080/api'
    ports:
      - '80:80'

  task-tracker-email-sender:
    build: './task-tracker-email-sender'
    restart: always
    ports:
      - '8081:8081'
    environment:
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
    depends_on:
      - kafka
      - zookeeper

  task-tracker-scheduler:
    build: './task-tracker-scheduler'
    restart: always
    ports:
      - '8082:8082'
    environment:
      DB_NAME: 'db'
      DB_USER: 'admin'
      DB_PASSWORD: 'admin'
      REPORT_CRON: '* * * * *'
    depends_on:
      - task-tracker-api
      - kafka
      - zookeeper

  mysql:
    image: mysql:8.0
    hostname: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
    expose:
      - '2181'

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    restart: always
    depends_on:
      - zookeeper
    expose:
      - '9092'
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_CREATE_TOPIC: 'EMAIL_SENDING_TASKS'

volumes:
  db:
    driver: local
